// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAizeDQ0Myl9wAATTOB4gC3WH9wFEl7GYo',
    appId: '1:354116918831:web:36d847a4ab7e796452f0da',
    messagingSenderId: '354116918831',
    projectId: 'quick-cash-a5c67',
    authDomain: 'quick-cash-a5c67.firebaseapp.com',
    storageBucket: 'quick-cash-a5c67.firebasestorage.app',
    measurementId: 'G-3DV9TCFYG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1IDflTwxHk6P5N41gM55brfdv3glRCgk',
    appId: '1:354116918831:android:49fc05196eb15ec652f0da',
    messagingSenderId: '354116918831',
    projectId: 'quick-cash-a5c67',
    storageBucket: 'quick-cash-a5c67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZzOT-2mY_3Zr9EdCsu_0k7cAHBkiH_g',
    appId: '1:354116918831:ios:c215b1e68b5213c452f0da',
    messagingSenderId: '354116918831',
    projectId: 'quick-cash-a5c67',
    storageBucket: 'quick-cash-a5c67.firebasestorage.app',
    iosBundleId: 'com.example.universityclassroommanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZzOT-2mY_3Zr9EdCsu_0k7cAHBkiH_g',
    appId: '1:354116918831:ios:c215b1e68b5213c452f0da',
    messagingSenderId: '354116918831',
    projectId: 'quick-cash-a5c67',
    storageBucket: 'quick-cash-a5c67.firebasestorage.app',
    iosBundleId: 'com.example.universityclassroommanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAizeDQ0Myl9wAATTOB4gC3WH9wFEl7GYo',
    appId: '1:354116918831:web:865088808f934eb152f0da',
    messagingSenderId: '354116918831',
    projectId: 'quick-cash-a5c67',
    authDomain: 'quick-cash-a5c67.firebaseapp.com',
    storageBucket: 'quick-cash-a5c67.firebasestorage.app',
    measurementId: 'G-4S2EHY1713',
  );
}
